---
title: "HW #1"
execute: 
  echo: false
---

# Assignment #1


## Due Date

> **Section 402:** Thursday, September 14 at 11:59 PM

This week's assignment will be broken into two parts:

## Part 1: Installing Python locally and launching a Jupyter notebook

Follow the [initial installation guide](https://musa-550-fall-2023.github.io/resource/install.html) on 
the course website for instructions on how to set up Python
locally and launch JupyterLab

Please see the [list of recommended readings](https://github.com/MUSA-550-Fall-2023/week-1#recommended-readings) for tutorials and background reading to get
familiar with Python, mamba/conda, and the Jupyter notebook.

**Problems?** Post your question to [Ed Discussion](https://edstem.org/us/courses/42616/discussion/)!


### Working Locally

If you've successfully followed the installation guide, you should be able to launch 
JupyterLab by running `jupyter lab` (after activating the course environment) from the command line. 
This should launch the [JupyterLab
dashboard](https://jupyterlab.readthedocs.io/en/stable/user/interface.html).
Now you can launch the assignment notebook "assignment-1.ipynb"
and get started on the homework!

The notebook will execute code from the current working directory (the folder
that the notebook was launched from). This folder is usually your home folder on
your laptop. If you are using relative file paths to load the data, the path
should be relative to this working directory. From within the Jupyter notebook,
you can find out the current working directory by running the following command
in a cell:

```python
pwd
```

If you've downloaded the [assignment-1](https://github.com/MUSA-550-Fall-2023/assignment-1) 
repository to your computer, it usually makes sense to launch the
Jupyter notebook from this folder instead of the default folder. You can
change the start-up folder by first navigating to your assignment folder in
the command line: see instructions [here](https://musa-550-fall-2023.github.io/resource/jupyter.html#changing-the-jupyterlab-start-up-folder).


## Part 2: Exploring the Donut Effect for Philadelphia ZIP codes


In part #2, you will explore the Donut Effect for home values in different parts of Philadelphia. This part will be submitted as a Jupyter notebook (a `.ipynb` file). There is already a starter notebook in this repository to help guide you through this part.

### Submission

**Note:** Be sure to read the documentation for assignment [guidelines](https://musa-550-fall-2023.github.io/assignment/overview.html#guidelines) and [submission](https://musa-550-fall-2023.github.io/assignment/overview.html#submission).

You will submit your assignment through GitHub. For each assignment, I will
provide a GitHub link that can be used to create a new repository. Each student
will have their own private repository on GitHub where the assignment can be
submitted. Only the student and instructors will have access to the private
repository.

The invitation link depends on your section. For this assignments, the links are:

> **Section 402**: [https://classroom.github.com/a/CGz9BQNG](https://classroom.github.com/a/CGz9BQNG)

If you do not have a GitHub account yet, you should be prompted to make an account. After clicking on this link, GitHub will create a new private repo with permissions such that only you and the instructors can view the commits.

Your assignment should be added to this newly crearted GitHub repository before the deadline. You can add files to the repository through the web (github.com) interface or using the command line on your laptop.

**Important**: Files should be committed to the newly created private repository (after following the above link) and _not_ to your forked version of the [assignment-1](https://github.com/MUSA-550-Fall-2023/assignment-1) repository.

**Your Jupyter notebook should be submitted to your private repository by the deadline.**
