---
title: "Week 2: Data Visualization Fundamentals"
execute: 
  echo: false
---

{{< include ../_header.qmd >}}

## Topics

- Color fundamentals and available tools
- Introduction to matplotlib, seaborn, and altair

## Recommended Readings

- [Guide to getting started with matplotlib](https://pbpython.com/effective-matplotlib.html)
- [Plotting & visualization chapter of Python for Data Analysis](https://wesmckinney.com/book/plotting-and-visualization)
  - A good introduction to plotting with matplotlib, pandas, and seaborn
- Altair:
  - [Introduction to Statistical Visualization](https://altair-viz.github.io/getting_started/starting.html)
  - [Interactive charts with altair](https://altair-viz.github.io/user_guide/interactions.html)
  - [Exploring Seattle Weather: A Case Study](https://altair-viz.github.io/case_studies/exploring-weather.html)
- Data viz design: [Introductory slides of London's design guidelines](https://data.london.gov.uk/blog/city-intelligence-data-design-guidelines/)

## Documentation

- [matplotlib](https://matplotlib.org/)
  - [Example plots](https://matplotlib.org/stable/gallery/index.html)
  - [Plot types](https://matplotlib.org/stable/plot_types/index.html)
- [seaborn docs homepage](https://seaborn.pydata.org/)
- [Seaborn tutorial](https://seaborn.pydata.org/tutorial.html)
  - [Visualizing statistical relationships](https://seaborn.pydata.org/tutorial/relational.html)
  - [Categorical data](https://seaborn.pydata.org/tutorial/categorical.html)
  - [Visualizing the distribution of a data set](https://seaborn.pydata.org/tutorial/distributions.html)
  - [Visualizing linear relationships](https://seaborn.pydata.org/tutorial/regression.html)
- [altair](https://altair-viz.github.io/)
  - [The user guide](https://altair-viz.github.io/user_guide/data.html)
  - [Example gallery](https://altair-viz.github.io/gallery/index.html)


## Other Readings

- [Remaking Historical Data Viz](https://towardsdatascience.com/how-to-remake-historical-data-visualization-and-why-you-should-c25874fc4804)
- [Modern Statistical Atlas](http://projects.flowingdata.com/atlas/)
- [A 6-part blog series on W. E. B. Du Bois' Data Visualization](https://towardsdatascience.com/w-e-b-du-bois-staggering-data-visualizations-are-as-powerful-today-as-they-were-in-1900-64752c472ae4)
- [Data Sketches](http://www.datasketch.es/)
- [The 7 Kinds of Data Visualization People](https://medium.com/visualizing-the-field/the-7-kinds-of-data-visualization-people-9964e80443a7)
- [Fast vs Slow Data Visualization](https://medium.com/@Elijah_Meeks/data-visualization-fast-and-slow-d2653d4850b0)
- [What Charts Say](https://medium.com/@Elijah_Meeks/what-charts-say-6e31cbba2047)
- [Color Guide and Overview of Color Tools](https://blog.datawrapper.de/colorguide/)
- [The Importance of Grey](http://www.visualisingdata.com/2015/01/make-grey-best-friend/)
- [2017 PyCon presentation by Jake VanderPlas](https://www.youtube.com/watch?v=FytuB8nFHPQ)
- [Interview with John Burn-Murdoch about his COVID Data Viz](https://medium.com/nightingale/how-john-burn-murdochs-influential-dataviz-helped-the-world-understand-coronavirus-6cb4a09795ae)

## Color Resources

- [ColorBrewer 2.0](http://colorbrewer2.org/)
- [Viz Palette](https://projects.susielu.com/viz-palette)
- [Adobe Color CC](https://color.adobe.com/explore)
- [Colorpicker for data](http://tristen.ca/hcl-picker)
- [Chroma.js Color Scale Helper](https://gka.github.io/palettes/)
- [Choosing Color Maps in Matplotlib](https://matplotlib.org/tutorials/colors/colormaps.html)
- [Choosing Color Palettes in seaborn](https://seaborn.pydata.org/tutorial/color_palettes.html)
- [Names of available color maps in Altair](https://vega.github.io/vega/docs/schemes/)
