---
title: "Week 3: More Interactive Data Viz, Intro to Vector Data & GeoPandas"
execute: 
  echo: false
---

{{< include ../_header.qmd >}}

## Topics

- Interactive data viz with the holoviz ecosystem
- Vector data and introduction to GeoPandas
- Spatial relationships and joins
- Demo: 311 requests by neighborhood in Philadelphia

## General Background Reading

Some general background readings that will help establish the
foundation for this week's work. From [Python for Data Analysis](https://wesmckinney.com/book/) by Wes McKinney:

- [Chatper 2: Python Basics](https://wesmckinney.com/book/python-basics)
- [Chapter 3: Built-in Python Features](https://wesmckinney.com/book/python-builtin)
- [Chapter 4: NumPy Basics](https://wesmckinney.com/book/numpy-basics)
- [Chapter 5: Intro to pandas](https://wesmckinney.com/book/pandas-basics)
- [Chapter 9: Plotting & visualization](https://wesmckinney.com/book/plotting-and-visualization)

## Documentation

- [GeoPandas](http://geopandas.org/)
  - [Choropleth Maps](https://geopandas.org/en/latest/docs/user_guide/mapping.html)
  - [Converting DataFrames to GeoDataFrames](https://geopandas.org/en/latest/gallery/create_geopandas_from_pandas.html)
  - [Managing Projections](https://geopandas.org/en/stable/docs/user_guide/projections.html)
  - [Merging Data](https://geopandas.org/en/latest/docs/user_guide/mergingdata.html)
- [Classification Schemes](https://pysal.org/mapclassify/api.html)

## Further Reading / References

- [West Wing and the Gall-Peters Projections](https://www.youtube.com/watch?v=vVX-PrBRtTY)
- [xkcd Comic on Projections](https://xkcd.com/977/)
- [The True Size Of](https://thetruesize.com/)
- [Coordinate Reference Systems](https://docs.qgis.org/2.8/en/docs/gentle_gis_introduction/coordinate_reference_systems.html)
- [EPSG Codes](http://epsg.io/)

