---
title: Python resources
---

{{< var course.number >}} assumes some general familiarity with programming 
concepts, but there aren't any formal Python prerequisites. However, we
recommend all students that they use some of the free, online resources
for learning Python's core concepts. Below, we include a number of online 
resources that are freely available for students in the course.

## DataCamp courses

DataCamp is providing 6 months of complimentary access to its courses for students 
in {{< var course.number >}}. Whether you have experience with Python or not, this is 
a great opportunity to learn the basics of Python and practice your skills. 

It is strongly recommended that you watch some or all of the introductory videos below 
to build a stronger Python foundation for the semester. The more advanced, 
intermediate courses are also great — the more the merrier!

::: {.callout-important}
To gain access, use [this unique invite link](https://www.datacamp.com/groups/shared_links/373f34169485d7eee55928c9fe0cdc3b676a5264eb6578ad62d5603eb631dce0). You will 
need to create or sign in to a DataCamp account with an "upenn.edu" email address.
:::

Introductory DataCamp courses include:

- [Introduction to Python for Data Science](https://www.datacamp.com/courses/intro-to-python-for-data-science)
- [Python Data Science Toolbox, Part 1](https://www.datacamp.com/courses/python-data-science-toolbox-part-1)
- [Python DataScience Toolbox, Part 2](https://www.datacamp.com/courses/python-data-science-toolbox-part-2)
- [Introduction to NumPy](https://www.datacamp.com/courses/introduction-to-numpy)



And there are also shorter, free tutorials available on some core Python concepts:

- [If/else statements](https://www.datacamp.com/tutorial/elif-statements-python)
- [For loops](https://www.datacamp.com/tutorial/for-loops-in-python)
- [While loops](https://www.datacamp.com/tutorial/python-while-loop)


A few courses covering more advanced topics include:

- [Intermediate Python](https://www.datacamp.com/courses/intermediate-python)
- [Writing functions in Python](https://www.datacamp.com/courses/writing-functions-in-python)

There are also courses available to help reinforce topics we will cover in detail
during the semester, including:

- [Data manipulation with pandas](https://www.datacamp.com/courses/data-manipulation-with-pandas)
- [Joining data with pandas](https://www.datacamp.com/courses/joining-data-with-pandas)
- [Introduction to Data Visualization with seaborn](https://www.datacamp.com/courses/introduction-to-data-visualization-with-seaborn)
- [Introduction to Data Visualization with matplotlib](https://www.datacamp.com/courses/introduction-to-data-visualization-with-matplotlib)
- [Intermediate Data Visualization with seaborn](https://www.datacamp.com/courses/intermediate-data-visualization-with-seaborn)
- [Supervised Learning with scikit-learn](https://www.datacamp.com/courses/supervised-learning-with-scikit-learn)


:::{.callout-tip}
Check out the full list of available Python courses [on DataCamp's website](https://www.datacamp.com/search?q=&tab=courses&facets%5Btechnology%5D%5B%5D=Python).
::: 


## Introductory Python tutorials

The following tutorials assume no background in Python and provide a fairly comprehensive introduction to Python and its core concepts.

- [Practical Python Programming](https://dabeaz-course.github.io/practical-python/Notes/Contents.html) by [David Beazley](https://twitter.com/dabeaz)
- [Python for Social Science](https://gawron.sdsu.edu/python_for_ss/course_core/book_draft/index.html) (in particular, the first four chapters)
- [Scientific Python Basics](https://bids.github.io/2016-01-14-berkeley/python/00-python-intro.html) from the Berkeley Institute for Data Science ([notebook version](https://bids.github.io/2016-01-14-berkeley/python/00-python-intro.ipynb))

## More in-depth resources

There are two books available online for free that can serve as good resources for introductory Python basics as 
well as more advanced data science concepts.

### Python for Data Analysis

The [Python for Data Analysis](https://wesmckinney.com/book/) book by Wes McKinney (the creator of Pandas)
is an excellent resource that covers the pandas library in great detail. The first 
few chapters are very good at covering the foundations of Python that we will use in this course:

- [Chatper 2: Python Basics](https://wesmckinney.com/book/python-basics)
- [Chapter 3: Built-in Python Features](https://wesmckinney.com/book/python-builtin)
- [Chapter 4: NumPy Basics](https://wesmckinney.com/book/numpy-basics)
- [Chapter 5: Intro to pandas](https://wesmckinney.com/book/pandas-basics)
- [Chapter 9: Plotting & visualization](https://wesmckinney.com/book/plotting-and-visualization)


### The Python Data Science Handbook
The [The Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) by [Jake VanderPlas](https://twitter.com/jakevdp) is a free, online textbook covering the Python basics needed for this course. It is a bit more advanced than the resources in the
previous section and assumes some familiarity with Python.

In particular, the first four chapters are excellent:

- [Chapter 1: IPython/Jupyter](https://jakevdp.github.io/PythonDataScienceHandbook/01.00-ipython-beyond-normal-python.html)
- [Chapter 2: Numpy](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html)
- [Chapter 3: Pandas](https://jakevdp.github.io/PythonDataScienceHandbook/03.00-introduction-to-pandas.html)
- [Chapter 4: matplotlib](https://jakevdp.github.io/PythonDataScienceHandbook/04.00-introduction-to-matplotlib.html)

The data analysis library `pandas` and the visualization library `matplotlib` will be covered extensively in this course, but the above chapters provide additional background material on this foundational Python tools.

**Note:** You can click on the "Open in Colab" button for each chapter and run the examples interactively in a cloud computing environment directly in the browser (using [Google Colab](https://colab.research.google.com)).

## Additional Resources

- The Berkeley Institute for Data Science has compiled a [number of Python resources](http://python.berkeley.edu/resources/)
- The subreddit [r/learnpython](https://www.reddit.com/r/learnpython) is a good place for Python resources — it maintains a comprehensive [wiki](https://www.reddit.com/r/learnpython/wiki/index) of resources and tutorials.
