---
title: "HW #3"
execute: 
  echo: false
---

{{< include ../shared/_header.qmd >}}


## Due Dates

> Section 401: October 23 by end of day

## Topics covered

- geopandas and spatial operations
- hvplot
- Raster data


## Description

This assignment will include two parts:

In Part 1, we'll explore spatial trends evictions in Philadelphia using data from the [Eviction Lab](https://evictionlab.org/) and building code violations using data from [OpenDataPhilly](https://www.opendataphilly.org/).

We'll be exploring the idea that evictions can occur as retaliation against renters for reporting code violations. Spatial correlations between evictions and code violations from the City's Licenses and Inspections department can offer some insight into this question.

In Part 2, we'll dive into the NDVI in Philadelphia more. Using Landsat data, we'll calculate the NDVI within
the city limits and compare it to the NDVI in the immediate suburbs. We'll also calculate the NDVI at the
locations of trees in Philadelphia, using a dataset of street trees from OpenDataPhilly.

### Background readings

- [HuffPost article](https://www.huffingtonpost.com/entry/cities-are-starting-to-pay-attention-to-the-eviction-crisis-thats-devastated-poor-tenants_us_5b1a7b21e4b0bbb7a0dbd59e)
- [PlanPhilly article](http://planphilly.com/articles/2018/04/12/philly-landlords-evict-more-people-than-owners-in-other-large-cities)
- [The Eviction Lab](https://evictionlab.org/)
- [Data Dictionary for Eviction Lab data](./eviction_lab_data_dictionary.txt) available for download in this repository

## Assignment details

A skeleton Jupyter notebook is available in this repository that will walk you through the steps of the assignment. The completed notebook should be submitted as your assignment.

## Submission

We'll be using GitHub for assignment submission again. You can set up your own private repository on GitHub for this assignment using the link below.

The invitation link will depend upon your section:

> Section 401: [https://classroom.github.com/a/_r-fhCLn](https://classroom.github.com/a/_r-fhCLn)


The assignment should be added to this GitHub repository before the deadline. You can add files to the repository through the web (github.com) interface or using the command line locally on your machine.
