---
title: "Final Project Proposal"
execute: 
  echo: false
---

{{< include ../shared/_header.qmd >}}

## Due date

Wednesday, December 6, 2023 at 11:59 PM

## Overview

Submit a short (1/2 to 1 page) proposal that outlines and describe your plan for the final project. The proposal should discuss the following aspects of the project:

- the data set(s) you wish to use in the project,
- the questions that you want to explore
- the analysis methods and techniques that you will use
- how the above items satisfy the requirements outlined in the [final project description](https://github.com/MUSA-550-Fall-2023/final-project)

The description of the final project can be found [here](https://github.com/MUSA-550-Fall-2023/final-project).

**Note:** if you are struggling to come up with ideas for datasets, analyses, etc, please reach out and we can discuss potential project ideas.

## Proposal deliverable

We will use GitHub Classroom to submit the proposal. Use the submission links below to create a private repository for your proposal. 
Then you will be able to upload a word document, PDF, Markdown file, etc. to the 
assignment's GitHub repository with your proposal.

## Group work

If you're working in groups for the final project, only one person needs to submit the proposal. However,
make sure you include all of the group members' names in the proposal!

## Submission

Submission link is:

> Section 402: [https://classroom.github.com/a/xAPP96O0](https://classroom.github.com/a/xAPP96O0)
