---
title: "Week 1: Exploratory Data Science in Python"
execute: 
  echo: false
---

{{< include ../_header.qmd >}}

## Topics

- Course Logistics
- Using Jupyter Notebooks
- Introduction to Pandas

## Initial Survey

Please fill out this anonymous survey for some initial feedback:

[https://bit.ly/musa550-initial-feedback](https://bit.ly/musa550-initial-feedback)

## Recommended Readings

- [Course syllabus](https://musa-550-fall-2023.github.io/syllabus.html)
- [Guide for installing Python and initial set up](https://musa-550-fall-2023.github.io/resource/install.html)
- [Guide for mamba/conda](https://musa-550-fall-2023.github.io/resource/mamba.html)
  - Check out [this 20-minute guide](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html) on the conda docs
- [Guide for Jupyter notebooks and JupyterLab](https://musa-550-fall-2023.github.io/resource/jupyter.html)
  - Good readings on the Jupyter docs include:
    - [Starting JupyterLab](https://jupyterlab.readthedocs.io/en/stable/getting_started/starting.html)
    - [The JupyterLab interface](https://jupyterlab.readthedocs.io/en/stable/user/interface.html)
    - [The structure of a notebook document](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#structure-of-a-notebook-document)
    - [The notebook workflow](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#basic-workflow)
    - [Working with notebooks in JupyterLab](https://jupyterlab.readthedocs.io/en/stable/user/notebook.html)
    - [Working with files](https://jupyterlab.readthedocs.io/en/stable/user/files.html)
- Recommended tutorial for students with little Python background: [Practical Python Programming](https://dabeaz-course.github.io/practical-python/Notes/Contents.html)



### Python tutorials & DataCamp access

A number of Python resources are listed on [the course website](https://musa-550-fall-2023.github.io/resource/python.html). In particular, 
DataCamp is providing 6 months of complimentary access to its courses for students in MUSA 550. Whether you have experience with Python or not, this is a great opportunity to learn the basics of Python and practice your skills.

It is strongly recommended that you watch some or all of the introductory videos below to build a stronger Python foundation for the semester. The more advanced, intermediate courses are also great — the more the merrier!

Check out [the resources page](https://musa-550-fall-2023.github.io/resource/python.html#datacamp-courses) for more
information, including how to sign up.


## Additional materials

### Documentation
- Git and GitHub:
  - [Setting up git](https://help.github.com/articles/set-up-git/)
  - [Managing files on GitHub](https://help.github.com/articles/managing-files-on-github/)
- [Conda user guide](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html)
- [Jupyter notebook](https://jupyter-notebook.readthedocs.io)
- [Guide to Markdown in notebook cells](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html)
- [Binder Documentation](https://mybinder.readthedocs.io/en/latest/)
- [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/)
- [matplotlib documentation](https://matplotlib.org/)

### Readings/reference

- [StackOverflow: The Incredible Growth of Python](https://stackoverflow.blog/2017/09/06/incredible-growth-python/)
- [2015 Funding Proposal for the Jupyter Notebook](https://blog.jupyter.org/project-jupyter-computational-narratives-as-the-engine-of-collaborative-data-science-2b5fb94c3c58)
- [A history of Jupyter Notebooks by its founder](https://web.archive.org/web/20180320053812/http://blog.fperez.org/2012/01/ipython-notebook-historical.html)
- [Google's Colab](https://colab.research.google.com/notebooks/welcome.ipynb)
- [Tidy Data](https://en.wikipedia.org/wiki/Tidy_data)
- [Joining Datasets](./joining_infographic.jpg)
- [ZIllow Data](https://www.zillow.com/research/data/)
- [Introduction to writing your first Python program](https://dabeaz-course.github.io/practical-python/Notes/01_Introduction/02_Hello_world.html)
- [Visual Studio Code](https://code.visualstudio.com/download)
